url: https://telosys.github.io
baseurl: 

# Site settings
title: Telosys
email: telosysteam@gmail.com
description: "Telosys - The latest and easiest code generator !"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Laurent Guérin
  pic: 1
  position: National Practice Leader
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Benoît Wilcox
  pic: 2
  position: Architecte Solution
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Ludovic Chaboud
  pic: 3
  position: Technical Expert Java
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/telosys
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/telosys
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/telosys-tools

# Postal address (add as many lines as necessary)
address:
  - line: 1 rue Charles Lindbergh - Immeuble Concorde
  - line: 44340 Bouguenais / France

# Build settings
markdown: kramdown
permalink: pretty